#### Welcome to NumPy Tutorial By -Munir ####

####   Installing Numpy Library to get started using Numpy ####

In [1]:
import numpy as np

In [2]:
print("Hello this is our python Numpy Library")

Hello this is our python Numpy Library


### The Basics  ###

In [3]:
#creating an Numpy Array
#To avoid writing functions manually type half words like ar then press tab it will open relevant functions like array() then hit enter

# A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0),
# and the second running horizontally across columns (axis 1).

myarr = np.array([1,2,3,4])

In [4]:
#printing an Numpy Array
myarr

array([1, 2, 3, 4])

In [5]:
#Accessing element in a array indexes start from 0 to onwards
myarr[1]

2

In [6]:
#Specifying data type to use array efficently
newarr =  np.array([1,2,3], np.int8 )

In [7]:
newarr

array([1, 2, 3], dtype=int8)

In [8]:
#Creating a 2D Array
arr2d = np.array([[1.0,2.4,7.3,2.5],[4.7, 3.9, 10.23, 2.3]], np.int16)
print(arr2d)

[[ 1  2  7  2]
 [ 4  3 10  2]]


In [9]:
#Get Dimension of Array
newarr.ndim

1

In [10]:
arr2d.ndim

2

In [11]:
#Get shape of Array(row, column)
arr2d.shape

(2, 4)

In [12]:
#Get type of an array
arr2d.dtype

dtype('int16')

In [13]:
#Returns size of an array in bytes(int16 = 8+8 bites in total)
arr2d.itemsize

2

In [14]:
#Get total size 
arr2d.nbytes

16

### Accessing/Changing specific elements/rows/columns, etc ###

In [15]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
a.shape

(2, 7)

In [17]:
#Get specific Element (r,c) (indexing is from 0 to onwards)
a[1,5]


13

In [18]:
#We can also use -ve values to access values
a[1,-2]

13

In [19]:
#Get a specific row (0= row , : means all columns)
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
#Get a specific column (: means all the rows , 2nd column)
a[: , 2]

array([ 3, 10])

In [21]:
#More Advance stuff (startindex:endindex:stepsize) (0= row, 1:6:2 means select 1 to 6th column (6th col excluded) and setpsize by 2 )
a[0, 1:6:2]

array([2, 4, 6])

In [22]:
a[0, 1:-1:2]

array([2, 4, 6])

In [23]:
#Changing an element (element at 2nd row and 6th col was changed to 26)
a[1,-3] = 26

In [24]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 26, 13, 14]])

In [25]:
#Changing whole column
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 26 13 14]]


In [26]:
#Replacing both values of column
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 26 13 14]]


In [27]:
#Changing whole row
a[1,:] = 1
print(a)

[[1 2 1 4 5 6 7]
 [1 1 1 1 1 1 1]]


### 3D Array Example ###

In [28]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [29]:
#Get specific elemnet (approach -work outside in) (0 means outside, 1 means second row, 1 means second column)
b[0,1,1]

4

In [30]:
b[0,2,0]

5

In [31]:
b[0,3,1]

8

In [32]:
#Create a 3d Array a (2x2x2) cube
cube = np.array([
    
[
    [1,2],
    [3,4]

],
                
[
    [5,6],
    [7,8]

]    
    
])

In [33]:
#Trick to access elements in a 3d Array

# Axis 0: This is the outermost dimension, representing different "slices" of the cube. In our example, it has a size of 2 because there are two slices of the cube (the two 2x2 grids).
# Axis 1: This represents the rows within each slice. It also has a size of 2 because each slice contains two rows.
# Axis 2: This represents the columns within each row. Again, it has a size of 2 because each row has two columns.

# cube[0, 0, 0]: This accesses the element in the first slice, first row, first column, which is 1.
# cube[0, 1, 1]: This accesses the element in the first slice, second row, second column, which is 4.
# cube[1, 0, 1]: This accesses the element in the second slice, first row, second column, which is 6.


In [34]:
cube[1,1,0] #second slice, second row and first column

7

### Initializing Different types of Array 

In [35]:
#All 0s matrix
np.zeros((2,3)) #returns a 2x3 2d matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.zeros((3,2,3)) #3 slice, each slice has 2 rows and each row has 3 columns

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
#All ones matrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
#Any other Number (parameters are shape(rxc) and value)
np.full((2,2),108,dtype='float32')

array([[108., 108.],
       [108., 108.]], dtype=float32)

In [39]:
#Any other number full_like (resuing existing array and replacing with new value)
np.full_like(cube,5)

array([[[5, 5],
        [5, 5]],

       [[5, 5],
        [5, 5]]])

In [40]:
#Random Decimal Numbers (parameter is rxc)
np.random.rand(4,2)

array([[0.91714972, 0.95013919],
       [0.9263982 , 0.56838091],
       [0.15403796, 0.39116546],
       [0.57459652, 0.13308901]])

In [41]:
np.random.random_sample(cube.shape) #same as full_like

array([[[0.32825147, 0.51294075],
        [0.21293344, 0.9535846 ]],

       [[0.84186564, 0.84960264],
        [0.10976402, 0.95959929]]])

In [42]:
#Random integer values (numbers only between 0 to 7(7 is exclusive)) 
np.random.randint(7, size=(3,3))

array([[1, 1, 6],
       [4, 4, 1],
       [5, 2, 5]])

In [43]:
np.random.randint(4,7, size=(3,3))

array([[5, 6, 4],
       [4, 4, 6],
       [4, 6, 5]])

In [44]:
#Identity Matrix (1s at diagonal position)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
#repeats an array in new array (parameters are array to repeat,num of times to repeat, axis)
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
test = np.ones((5,5))
print(test)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
z =  np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [48]:
test[1:4,1:4] = z #(1:4 means 1 to 4 rows (4 is excluded) and 1 to 4 means columns selected but 4 is ecluded)
print(test)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
#Copying an array
cp = np.array([1,2,3])
b = cp.copy()
b[0] = 100
print(b)

[100   2   3]


### Mathematics ###

In [50]:
#Element wise add,sub,mult,div,pow
a = np.array([5,2,4,2])
print(a)

[5 2 4 2]


In [51]:
a+2

array([7, 4, 6, 4])

In [52]:
a-2

array([3, 0, 2, 0])

In [53]:
a*2

array([10,  4,  8,  4])

In [54]:
a/2

array([2.5, 1. , 2. , 1. ])

In [55]:
b = np.array([1,0,1,0])
a+b

array([6, 2, 5, 2])

In [56]:
a ** 2

array([25,  4, 16,  4])

In [57]:
#Trignometry
np.sin(a)

array([-0.95892427,  0.90929743, -0.7568025 ,  0.90929743])

In [58]:
np.cos(a)

array([ 0.28366219, -0.41614684, -0.65364362, -0.41614684])

In [59]:
np.tan(b)

array([1.55740772, 0.        , 1.55740772, 0.        ])

### Linear Algebra ###

In [60]:
#In order to multiply a matrix in linear algebra columns of first matrix and rows of 2nd matrix must be same and resultant is 2x2
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [61]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [62]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [63]:
#Determinant of a Matrix
c =  np.identity(3)
np.linalg.det(c)

1.0

In [64]:
#Inverse of a matrix
i = np.array(
    [
        [1,2],
        [3,4]
    ]
)
i_inv = np.linalg.inv(i)
print("Original Matrix: ")
print(i)
print("Inverse Matrix:")
print(i_inv)

Original Matrix: 
[[1 2]
 [3 4]]
Inverse Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


### Statistics ###

In [65]:
stats = np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
np.min(stats)

1

In [67]:
np.min(stats, axis=1) #minimum value from each row

array([1, 5])

In [68]:
np.max(stats)

8

In [69]:
np.sum(stats) #sums up all the element in the matrix

36

In [70]:
np.sum(stats,axis=0)

array([ 6,  8, 10, 12])

### Reorganizing Arrays ###

In [71]:
#Used to convert previous array into new custom shape array like (2,4) can be converted into (2,2,2) or (4,2)
before = np.array([[1,2,3,4,],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [72]:
#Vertically stacking vectors/matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

#little fancy
np.vstack([v2,v1,v1,v2,v1])


array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [73]:
#Horizontal Stacking
h1 = np.zeros((2,4))
h2 = np.ones((2,2))

#h2 on back of h1
np.hstack([h1,h2])


array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

### Miscellaneous ###

# Loading Data from File #

In [74]:
filedata = np.genfromtxt('practice_data.txt',delimiter=',')
# np.shape(filedata)  => (3,18)

filedata = filedata.astype('int32') #copy filedata variable values into int32 format

print(filedata)


[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [75]:
filedata[2,3]

11

### Boolean Masking and Advance Indexing ###

In [76]:
#where in filedata value greater then 50 (can also do other comparison operators like <,<=,>=,!=)
filedata >= 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [77]:
#Index based on greater then 50 (you get only those values that are greater then 50)
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [78]:
#Note: You can index with the list in Numpy
a= np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [79]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [80]:
np.all(filedata > 50, axis=0) #in axis= 0 it evaluates vertically downward and each row value must be greater then 50 to evalue to true

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [81]:
np.any(filedata > 50, axis=1) #axis=1 it evaluates values according to columns considering values from all columns (left to righ)

array([ True,  True,  True])

In [82]:
((filedata > 50) & (filedata > 100))

array([[False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [83]:
#fancy
result = np.sum((filedata > 50) & (filedata > 100), axis=1)
print(result)

[1 1 1]


In [84]:
( ~( (filedata > 50) & (filedata > 50) ) ) #Not of result

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])